/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.SessionManager;
import config.config;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import main.LOGin;

/**
 *
 * @author Administrator
 */
public class userTASK extends javax.swing.JFrame {

    /**
     * Creates new form TASK
     */
  public userTASK() {
        initComponents();
        if (!SessionManager.getInstance().isLoggedIn() ||
            !"User".equals(SessionManager.getInstance().getUserType())) {
            javax.swing.JOptionPane.showMessageDialog(null,
                "Access Denied! Please log in first.",
                "Unauthorized", javax.swing.JOptionPane.ERROR_MESSAGE);
            LOGin log = new LOGin();   // ← goes directly to LOGin
            log.setVisible(true);
            this.dispose();
            return;
        }
        displayAssignedTasks();
    }
    
    // ── Load only tasks assigned to the current user ────────────────────────
   private void displayAssignedTasks() {
    int currentUserId = SessionManager.getInstance().getUserId();

    // ✅ ADDED REMARKS to the SELECT statement
    String sql = "SELECT T.TASK_ID, T.DATE_CREATED, T.TASK, T.DESCRIPTION, T.CREATEDBY, T.STATUS, T.DUE_DATE, T.REMARKS, A.ROLE "
               + "FROM \"ASSIGNED TASK\" A "
               + "JOIN Task T ON A.TASKASSIGNED = T.TASK_ID "
               + "WHERE A.ASSINGEDTO = ?";

    try (Connection conn = config.connectDB();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        pstmt.setInt(1, currentUserId);

        try (ResultSet rs = pstmt.executeQuery()) {
            Vector<String> columns = new Vector<>();
            columns.add("Task ID");
            columns.add("Date Created");
            columns.add("Title");
            columns.add("Description");
            columns.add("Created By");
            columns.add("Status");
            columns.add("Due Date");
            columns.add("Remarks");  // ✅ ADD THIS
            columns.add("Role");

            Vector<Vector<Object>> data = new Vector<>();
            while (rs.next()) {
                Vector<Object> row = new Vector<>();
                row.add(rs.getInt("TASK_ID"));
                row.add(rs.getInt("DATE_CREATED"));
                row.add(rs.getString("TASK"));
                row.add(rs.getString("DESCRIPTION"));
                row.add(rs.getInt("CREATEDBY"));
                row.add(rs.getString("STATUS"));
                row.add(rs.getString("DUE_DATE"));
                row.add(rs.getString("REMARKS"));  // ✅ ADD THIS
                row.add(rs.getString("ROLE"));
                data.add(row);
            }

            DefaultTableModel model = new DefaultTableModel(data, columns) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            TaskTable.setModel(model);
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error loading assigned tasks: " + e.getMessage(),
            "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        prof = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        TASK = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaskTable = new javax.swing.JTable();
        update = new javax.swing.JButton();
        VIEW = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USER DASHBOARD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 290, 60));

        prof.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profMouseClicked(evt);
            }
        });
        jPanel2.add(prof, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 120, 80));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 580, 80);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 23));

        TASK.setBackground(new java.awt.Color(0, 102, 204));
        TASK.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        TASK.setText("TASK");
        TASK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TASKActionPerformed(evt);
            }
        });
        jPanel3.add(TASK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, -1));

        jButton3.setBackground(new java.awt.Color(0, 153, 204));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton3.setText("PRINT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, -1));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(410, 80, 170, 310);

        TaskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TaskTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 390, 190);

        update.setBackground(new java.awt.Color(0, 102, 204));
        update.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(300, 100, 100, 30);

        VIEW.setBackground(new java.awt.Color(0, 102, 204));
        VIEW.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        VIEW.setText("VIEW");
        VIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEWActionPerformed(evt);
            }
        });
        jPanel1.add(VIEW);
        VIEW.setBounds(220, 100, 73, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        LOGin log = new LOGin();
        log.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void TASKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TASKActionPerformed
        userTASK T = new userTASK();
        T.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_TASKActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        int selectedRow = TaskTable.getSelectedRow();

        // ── Validation: user must select a row first ─────────────────────────
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select a task from the table first before clicking UPDATE.",
                "No Task Selected", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // stop here, do not open updateTask
        }

        // ── Read all column values from the selected row ──────────────────────
        // Column order: 0=Task ID, 1=Date Created, 2=Title, 3=Description,
        //               4=Created By, 5=Status, 6=Due Date, 7=Role
        int    taskId      = (int)    TaskTable.getValueAt(selectedRow, 0);
        String dateCreated = String.valueOf(TaskTable.getValueAt(selectedRow, 1));
        String task        = (String) TaskTable.getValueAt(selectedRow, 2);
        String description = (String) TaskTable.getValueAt(selectedRow, 3);
        String createdBy   = String.valueOf(TaskTable.getValueAt(selectedRow, 4));
        String status      = (String) TaskTable.getValueAt(selectedRow, 5);
        String dueDate     = (String) TaskTable.getValueAt(selectedRow, 6);
        String role        = (String) TaskTable.getValueAt(selectedRow, 7);

        // Open updateTask with the selected task's data pre-filled
        updateTask tsk = new updateTask(taskId, dateCreated, task, description, createdBy, status, dueDate, role);
        tsk.setVisible(true);
        this.dispose();


// TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void VIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEWActionPerformed
        
       int selectedRow = TaskTable.getSelectedRow();
    
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Please select a task from the table first.",
            "No Task Selected", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // ✅ UPDATED: Get values including REMARKS (index 7)
    String dateCreated = String.valueOf(TaskTable.getValueAt(selectedRow, 1));
    String task = (String) TaskTable.getValueAt(selectedRow, 2);
    String description = (String) TaskTable.getValueAt(selectedRow, 3);
    String status = (String) TaskTable.getValueAt(selectedRow, 5);
    String dueDate = (String) TaskTable.getValueAt(selectedRow, 6);
    String remarks = (String) TaskTable.getValueAt(selectedRow, 7);  // ✅ GET REMARKS
    
    // Open viewTask with data including remarks
    viewTask vew = new viewTask(dateCreated, dueDate, task, description, status, remarks);
    vew.setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_VIEWActionPerformed

    private void profMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profMouseClicked
        view v = new view ();
        v.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_profMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TRY T = new TRY();
        T.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userTASK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userTASK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userTASK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userTASK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userTASK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TASK;
    private javax.swing.JTable TaskTable;
    private javax.swing.JButton VIEW;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel prof;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
