/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.SessionManager;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import main.LOGin;


/**
 *
 * @author Administrator
 */
public class view extends javax.swing.JFrame {
    private static final String DEFAULT_IMAGE_RESOURCE = "/image/Profile.png";
   private final String imagePackagePath;

   public view() {
    imagePackagePath = System.getProperty("user.dir") + File.separator
        + "src" + File.separator + "image" + File.separator;
    initComponents();
    loadUserProfile();
    loadProfileImage();  // <-- ADD THIS LINE
}

    /**
     * Loads the logged-in user's info from the session — no extra DB query needed.
     */
    private void loadUserProfile() {
    SessionManager session = SessionManager.getInstance();

    if (!session.isLoggedIn()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Access Denied! Please log in first.",
            "Unauthorized", javax.swing.JOptionPane.WARNING_MESSAGE);
        new LOGin().setVisible(true);
        this.dispose();
        return;
    }

    String[] columns = {"FIELD", "INFO"};
    Object[][] data = {
        {"ID",       session.getUserId()},
        {"NAME",     session.getUserName()},
        {"EMAIL",    session.getUserEmail()},
        {"PASSWORD", session.getUserPassword()},
        {"TYPE",     session.getUserType()},
        {"STATUS",   session.getUserStatus()}
    };

    table.setModel(new javax.swing.table.DefaultTableModel(data, columns) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    });
}
    private void loadProfileImage() {
    SessionManager session = SessionManager.getInstance();

    String fileName = "profile_" + session.getUserId() + ".png";
    File file = new File(imagePackagePath + fileName);

    ImageIcon icon;

    if (file.exists()) {
        icon = new ImageIcon(file.getAbsolutePath());
    } else {
        java.net.URL url = getClass().getResource("/image/Profile.png");
        icon = (url != null) ? new ImageIcon(url) : null;
    }

    if (icon != null) {
        Image img = icon.getImage().getScaledInstance(130, 100, Image.SCALE_SMOOTH);
        newprof.setIcon(new ImageIcon(img));
    }
}
 
    private void editProfileImage() {
    SessionManager session = SessionManager.getInstance();
    JFileChooser chooser = new JFileChooser();
    chooser.setFileFilter(new FileNameExtensionFilter("Image Files", "png", "jpg", "jpeg"));

    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        File selected = chooser.getSelectedFile();

        // 🔥 Ensure folder exists
        File dir = new File(imagePackagePath);
        if (!dir.exists()) {
            dir.mkdirs();
        }

        // 🔥 Save inside src/image
        String newFileName = "profile_" + session.getUserId() + ".png";
        File destination = new File(imagePackagePath + newFileName);

        try {
            Files.copy(selected.toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);

            loadProfileImage();

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Image saved in src/image successfully!");
        } catch (IOException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error saving image: " + e.getMessage());
        }
    }
}

private void deleteProfileImage() {
    SessionManager session = SessionManager.getInstance();
    // Path to the custom user file
    String customFileName = "profile_" + session.getUserId() + ".png";
    File customFile = new File(imagePackagePath + customFileName);

    if (customFile.exists()) {
        if (customFile.delete()) {
            // Once deleted, loadProfileImage will naturally fall back to Profile.png
            loadProfileImage();
            javax.swing.JOptionPane.showMessageDialog(this, "Custom profile deleted. Restored default.");
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "You are already using the default profile.");
    }
}

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        newprof = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROFILE ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 290, 60));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 600, 80);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 390, 200);

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 90, 90, 27);
        jPanel1.add(newprof);
        newprof.setBounds(440, 90, 140, 100);

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 310, 90, 20);

        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit);
        edit.setBounds(440, 190, 60, 23);

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(500, 190, 80, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        UpdateProfile up = new UpdateProfile();
        up.setVisible(true);
        this.dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       user back = new user();
       back.setVisible(true);
       this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
         deleteProfileImage();
// TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
          editProfileImage();
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new view().setVisible(true));
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel newprof;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
