/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;
import config.config;
import javax.swing.JOptionPane;
import config.SessionManager;
import main.LOGin;
/**
 *
 * @author Administrator
 */
public class ADDUSER extends javax.swing.JFrame {

    /**
     * Creates new form ADDUSER
     */
    public ADDUSER() {
        initComponents();

        // ✅ CORRECT - uses SessionManager directly, NOT config.SessionManager
        if (!SessionManager.getInstance().isLoggedIn() ||
            !"Admin".equals(SessionManager.getInstance().getUserType())) {
            javax.swing.JOptionPane.showMessageDialog(null,
                "Access Denied! Please log in first.",
                "Unauthorized", javax.swing.JOptionPane.ERROR_MESSAGE);
            LOGin log = new LOGin();   // ← goes directly to LOGin
            log.setVisible(true);
            this.dispose();
            return;
        }
    }
 private boolean isPasswordSecure(String password) {
    // Customize these requirements as needed:
    boolean hasMinLength = password.length() >= 8;
    boolean hasUpperCase = password.matches(".*[A-Z].*");
    boolean hasLowerCase = password.matches(".*[a-z].*");
    boolean hasNumber = password.matches(".*\\d.*");
    boolean hasSpecialChar = password.matches(".*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>/?].*");
    boolean hasNoSpaces = !password.contains(" ");
    
    // All requirements must be met
    return hasMinLength && hasUpperCase && hasLowerCase && 
           hasNumber && hasSpecialChar && hasNoSpaces;
}
 
 private boolean isEmailExists(String email) {
    String sql = "SELECT COUNT(*) as count FROM ACCOUNTS WHERE email = ?";
    
    try (java.sql.Connection conn = config.connectDB();
         java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
        
        pstmt.setString(1, email);
        try (java.sql.ResultSet rs = pstmt.executeQuery()) {
            if (rs.next()) {
                return rs.getInt("count") > 0;
            }
        }
    } catch (java.sql.SQLException e) {
        System.out.println("Error checking email: " + e.getMessage());
    }
    return false;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        back = new javax.swing.JButton();
        add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD USER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 290, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 80));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("EMAIL:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 70, 40));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("PASSWORD:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 100, 40));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("NAME:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 70, 40));

        name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 150, 30));

        email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 150, 30));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 150, 30));

        back.setBackground(new java.awt.Color(0, 102, 204));
        back.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        add.setBackground(new java.awt.Color(0, 102, 204));
        add.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        userView view = new userView();
        view.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        
         if (name.getText().trim().isEmpty() || email.getText().trim().isEmpty() || password.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, 
            "All fields are required!",
            "Validation Error",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String userEmail = email.getText().trim();
    String userPassword = password.getText();
    String userName = name.getText().trim();
    
    // 2. Check if email already exists
    if (isEmailExists(userEmail)) {
        JOptionPane.showMessageDialog(null, 
            "This email is already registered!\n\n" +
            "Please use a different email address.",
            "Email Already Exists",
            JOptionPane.ERROR_MESSAGE);
        email.setText("");
        email.requestFocus();
        return;
    }
    
    // 3. Validate password
    if (!isPasswordSecure(userPassword)) {
        JOptionPane.showMessageDialog(null, 
            "Insecure Password!\n\n" +
            "Your password must meet these requirements:\n" +
            "• At least 8 characters long\n" +
            "• At least one uppercase letter (A-Z)\n" +
            "• At least one lowercase letter (a-z)\n" +
            "• At least one number (0-9)\n" +
            "• At least one special character (!@#$%^&*)\n\n" +
            "Please create a stronger password.",
            "Password Validation Failed",
            JOptionPane.ERROR_MESSAGE);
        password.setText("");
        password.requestFocus();
        return;
    }
    
    // 4. Add record to database
    try {
        config con = new config();
        String sql = "INSERT INTO ACCOUNTS (name, email, password, type, status) VALUES (?, ?, ?, ?, ?)";
        con.addRecord(sql, userName, userEmail, userPassword, "Unknown", "Pending");
        
        JOptionPane.showMessageDialog(null, 
            "REGISTRATION SUCCESSFUL!\n\n" +
            "Welcome, " + userName + "!\n" +
            "Your account has been created and is pending approval.",
            "Success",
            JOptionPane.INFORMATION_MESSAGE);
        
        // Clear fields and go to login
        name.setText("");
        email.setText("");
        password.setText("");
        
     
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, 
            "Registration Error: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }



// TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADDUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADDUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADDUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADDUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDUSER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
