/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.SessionManager;
import config.config;
import java.sql.Connection;
import java.sql.PreparedStatement;
import main.LOGin;

/**
 *
 * @author Administrator
 */
public class UpdateTask extends javax.swing.JFrame {

    /**
     * Creates new form UpdateTask
     */
    public UpdateTask() {
        initComponents();
        if (!SessionManager.getInstance().isLoggedIn() ||
            !"Admin".equals(SessionManager.getInstance().getUserType())) {
            javax.swing.JOptionPane.showMessageDialog(null,
                "Access Denied! Please log in first.",
                "Unauthorized", javax.swing.JOptionPane.ERROR_MESSAGE);
            SessionManager.getInstance().clearSession();
            new LOGin().setVisible(true);
            this.dispose();
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UP_DATE = new javax.swing.JTextField();
        UP_DUE = new javax.swing.JTextField();
        UP_TASK = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        UP_DESCRIPTION = new javax.swing.JTextArea();
        Task = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN DASHBOARD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 290, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 80));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("TASK:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, 20));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("DESCRIPTION:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 100, 20));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("DUE DATE:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 20));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("DATE:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 20));

        UP_DATE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        UP_DATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UP_DATEActionPerformed(evt);
            }
        });
        jPanel4.add(UP_DATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 240, -1));

        UP_DUE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        UP_DUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UP_DUEActionPerformed(evt);
            }
        });
        jPanel4.add(UP_DUE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 240, -1));

        UP_TASK.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        UP_TASK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UP_TASKActionPerformed(evt);
            }
        });
        jPanel4.add(UP_TASK, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 240, -1));

        UP_DESCRIPTION.setColumns(20);
        UP_DESCRIPTION.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        UP_DESCRIPTION.setRows(5);
        jScrollPane1.setViewportView(UP_DESCRIPTION);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 290, 90));

        Task.setBackground(new java.awt.Color(0, 102, 204));
        Task.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Task.setText("CONFIRM");
        Task.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaskMouseClicked(evt);
            }
        });
        Task.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskActionPerformed(evt);
            }
        });
        jPanel4.add(Task, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 420, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UP_DATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UP_DATEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UP_DATEActionPerformed

    private void UP_DUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UP_DUEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UP_DUEActionPerformed

    private void UP_TASKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UP_TASKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UP_TASKActionPerformed

    private void TaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaskMouseClicked
        String DATE_CREATEDInput  = UP_DATE.getText().trim();
        String DUE_DATEInput      = UP_DUE.getText().trim();
        String TASKInput          = UP_TASK.getText().trim();
        String DESCRIPTIONInput   = UP_DESCRIPTION.getText().trim();

        // Use session for CREATEDBY (INTEGER) and creator name for display
        SessionManager session    = SessionManager.getInstance();
        int    createdById        = session.getUserId();    // INTEGER — matches DB column type
        String createdByName      = session.getUserName();  // for display only

        // Validation — all required fields must be filled
        if (TASKInput.isEmpty() || DATE_CREATEDInput.isEmpty() || DUE_DATEInput.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please fill in all required fields (Task, Date Created, Due Date).",
                "Input Required", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Confirm before saving
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Would you like to save this task?",
            "Confirm", javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

        String sql = "INSERT INTO Task (CREATEDBY, TASK, DESCRIPTION, DATE_CREATED, DUE_DATE, STATUS, REMARKS) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?)";

        try (Connection conn = config.connectDB();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, createdById);          // INTEGER — correct type for CREATEDBY
            pstmt.setString(2, TASKInput);
            pstmt.setString(3, DESCRIPTIONInput);
            pstmt.setString(4, DATE_CREATEDInput);
            pstmt.setString(5, DUE_DATEInput);
            pstmt.setString(6, "Pending");         // meaningful default STATUS
            pstmt.setString(7, "None");            // meaningful default REMARKS

            pstmt.executeUpdate();

            javax.swing.JOptionPane.showMessageDialog(this,
                "Task saved successfully!\nCreated by: " + createdByName,
                "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Navigate back to task list
            viewTask vt = new viewTask();
            vt.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error saving task: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_TaskMouseClicked

    private void TaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaskActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        viewTask vt = new viewTask();
        vt.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        viewTask vt = new viewTask();
        vt.setVisible(true);
        this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Task;
    private javax.swing.JTextField UP_DATE;
    private javax.swing.JTextArea UP_DESCRIPTION;
    private javax.swing.JTextField UP_DUE;
    private javax.swing.JTextField UP_TASK;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
