/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.config;
import main.LOGin;
import config.SessionManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER27
 */
public class userView extends javax.swing.JFrame {

    /**
     * Creates new form userView
     */
   public userView() {
     initComponents();

        // ✅ CORRECT - uses SessionManager directly, NOT config.SessionManager
        if (!SessionManager.getInstance().isLoggedIn() ||
            !"Admin".equals(SessionManager.getInstance().getUserType())) {
            javax.swing.JOptionPane.showMessageDialog(null,
                "Access Denied! Please log in first.",
                "Unauthorized", javax.swing.JOptionPane.ERROR_MESSAGE);
            LOGin log = new LOGin();   // ← goes directly to LOGin
            log.setVisible(true);
            this.dispose();
            return;
        }

        displayUser();
}
    void displayUser(){
        config con = new config();
        String sql = "SELECT * FROM ACCOUNTS";
        con.displayData(sql, usertable);
    
    }
    
    void searchUser(String keyword) {
        if (keyword == null || keyword.trim().isEmpty()) {
            displayUser(); // If empty, show all
            return;
        }

        String sql = "SELECT * FROM ACCOUNTS WHERE "
                   + "name LIKE ? OR "
                   + "email LIKE ? OR "
                   + "type LIKE ? OR "
                   + "status LIKE ?";

        String pattern = "%" + keyword.trim() + "%";

        try (Connection conn = config.connectDB();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, pattern);
            pstmt.setString(2, pattern);
            pstmt.setString(3, pattern);
            pstmt.setString(4, pattern);

            try (ResultSet rs = pstmt.executeQuery()) {
                int colCount = rs.getMetaData().getColumnCount();
                Vector<String> columns = new Vector<>();
                for (int i = 1; i <= colCount; i++) {
                    columns.add(rs.getMetaData().getColumnName(i));
                }

                Vector<Vector<Object>> rows = new Vector<>();
                while (rs.next()) {
                    Vector<Object> row = new Vector<>();
                    for (int i = 1; i <= colCount; i++) {
                        row.add(rs.getObject(i));
                    }
                    rows.add(row);
                }

                DefaultTableModel model = new DefaultTableModel(rows, columns) {
                    @Override
                    public boolean isCellEditable(int row, int col) { return false; }
                };
                usertable.setModel(model);

                if (rows.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(null,
                        "No users found for: " + keyword.trim(),
                        "No Results", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null,
                "Search Error: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private boolean isPasswordSecure(String password) {
    // Customize these requirements as needed:
    boolean hasMinLength = password.length() >= 8;
    boolean hasUpperCase = password.matches(".*[A-Z].*");
    boolean hasLowerCase = password.matches(".*[a-z].*");
    boolean hasNumber = password.matches(".*\\d.*");
    boolean hasSpecialChar = password.matches(".*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>/?].*");
    boolean hasNoSpaces = !password.contains(" ");
    
    // All requirements must be met
    return hasMinLength && hasUpperCase && hasLowerCase && 
           hasNumber && hasSpecialChar && hasNoSpaces;
}
    
    private boolean isEmailExists(String email) {
    String sql = "SELECT COUNT(*) as count FROM ACCOUNTS WHERE email = ?";
    
    try (java.sql.Connection conn = config.connectDB();
         java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
        
        pstmt.setString(1, email);
        try (java.sql.ResultSet rs = pstmt.executeQuery()) {
            if (rs.next()) {
                return rs.getInt("count") > 0;
            }
        }
    } catch (java.sql.SQLException e) {
        System.out.println("Error checking email: " + e.getMessage());
    }
    return false;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usertable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        ADDUSER = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        UPDATE = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        DELETE = new javax.swing.JLabel();
        SEARCH = new javax.swing.JTextField();
        Search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN DASHBOARD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 290, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 80));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HOME");
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 150, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOGOUT");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 254, 60, 30));

        user.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setText("VIEW USER");
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        jPanel3.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 70, 30));

        user1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        user1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user1.setText("CREATE TASK");
        user1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user1MouseClicked(evt);
            }
        });
        jPanel3.add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VIEW ASSIGNED TASK");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 150, 310));

        usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(usertable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 400, 200));

        jPanel4.setBackground(new java.awt.Color(0, 0, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ADDUSER.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ADDUSER.setForeground(new java.awt.Color(255, 255, 255));
        ADDUSER.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ADDUSER.setText("ADD USER");
        ADDUSER.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ADDUSERMouseDragged(evt);
            }
        });
        ADDUSER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDUSERMouseClicked(evt);
            }
        });
        jPanel4.add(ADDUSER, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -1, 90, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 80, 30));

        jPanel6.setBackground(new java.awt.Color(0, 0, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UPDATE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        UPDATE.setForeground(new java.awt.Color(255, 255, 255));
        UPDATE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UPDATE.setText("UPDATE");
        UPDATE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UPDATEMouseClicked(evt);
            }
        });
        jPanel6.add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 80, 30));

        jPanel5.setBackground(new java.awt.Color(0, 0, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DELETE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DELETE.setForeground(new java.awt.Color(255, 255, 255));
        DELETE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DELETE.setText("DELETE");
        DELETE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETEMouseClicked(evt);
            }
        });
        jPanel5.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 80, 30));

        SEARCH.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });
        jPanel1.add(SEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 220, 30));

        Search.setBackground(new java.awt.Color(0, 102, 204));
        Search.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
            
        SessionManager.getInstance().clearSession();
        LOGin log = new LOGin();
            log.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        admin ad = new admin();
        ad.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseDragged

    private void UPDATEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseClicked
        try {
        // Get the selected row
        int selectedRow = usertable.getSelectedRow();
        
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please select a user to update!");
            return;
        }
        
        // Get current values (assuming column order: acc_id, name, email, password, type, status)
        String currentId = usertable.getValueAt(selectedRow, 0).toString();
        String username = usertable.getValueAt(selectedRow, 1).toString();
        String currentType = usertable.getValueAt(selectedRow, 4).toString();
        String currentStatus = usertable.getValueAt(selectedRow, 5).toString();
        
        // Type dropdown
        String[] types = {"Admin", "User"};
        String newType = (String) javax.swing.JOptionPane.showInputDialog(this,
            "Select user type for: " + username,
            "Update User Type",
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            types,
            currentType);
        
        if (newType == null) {
            return; // User cancelled
        }
        
        // Status dropdown
        String[] statuses = {"Active", "Pending", "Inactive"};
        String newStatus = (String) javax.swing.JOptionPane.showInputDialog(this,
            "Select status for: " + username,
            "Update User Status",
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            statuses,
            currentStatus);
        
        if (newStatus == null) {
            return; // User cancelled
        }
        
        // Update database
        String sql = "UPDATE ACCOUNTS SET type = ?, status = ? WHERE acc_id = ?";
        
        try (java.sql.Connection conn = config.connectDB();
             java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, newType);
            pstmt.setString(2, newStatus);
            pstmt.setString(3, currentId);
            
            int rowsAffected = pstmt.executeUpdate();
            
            if (rowsAffected > 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "User updated successfully!\n\n" +
                    "Updated Record (ID: " + currentId + "):\n" +
                    "Username: " + username + "\n" +
                    "Type: " + newType + "\n" +
                    "Status: " + newStatus);
                
                displayUser(); // Refresh table
            }
            
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Database Error: " + e.getMessage());
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_UPDATEMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
            admin ad = new admin();
            ad.setVisible(true);
            this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        userView view = new userView();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userMouseClicked

    private void DELETEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETEMouseClicked
        try {
        int selectedRow = usertable.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select a user to delete!");
            return;
        }

        String currentId = usertable.getValueAt(selectedRow, 0).toString();
        String username  = usertable.getValueAt(selectedRow, 1).toString();

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete: " + username + "?",
            "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

        String sql = "DELETE FROM ACCOUNTS WHERE acc_id = ?";

        try (java.sql.Connection conn = config.connectDB();
             java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, currentId);
            int rowsAffected = pstmt.executeUpdate();

            if (rowsAffected > 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "User \"" + username + "\" deleted successfully!");

                displayUser(); // Refresh table
            }

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Database Error: " + e.getMessage());
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage());
    }            // TODO add your handling code here:
    }//GEN-LAST:event_DELETEMouseClicked

    private void user1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1MouseClicked

        TASK ts = new TASK();
        ts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_user1MouseClicked

    private void ADDUSERMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDUSERMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDUSERMouseDragged

    private void ADDUSERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDUSERMouseClicked
            ADDUSER add = new ADDUSER();
            add.setVisible(true);
            this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_ADDUSERMouseClicked

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed

        searchUser(SEARCH.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_SEARCHActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        searchUser(SEARCH.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        viewAssigned ASS = new viewAssigned();
        ASS.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADDUSER;
    private javax.swing.JLabel DELETE;
    private javax.swing.JTextField SEARCH;
    private javax.swing.JButton Search;
    private javax.swing.JLabel UPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel user;
    private javax.swing.JLabel user1;
    private javax.swing.JTable usertable;
    // End of variables declaration//GEN-END:variables
}
